steps:
# copy over staging or production configurations
- name: 'gcr.io/cloud-builders/gsutil'
  args: ["cp", "appengine/form_data/app.$BRANCH_NAME.yaml", "appengine/form_data/app.yaml"]
- name: 'gcr.io/cloud-builders/gsutil'
  args: ["cp", "appengine/form_data_paperform/app.$BRANCH_NAME.yaml", "appengine/form_data_paperform/app.yaml"]
- name: 'gcr.io/cloud-builders/gsutil'
  args: ["cp", "appengine/datastore-backup/app.$BRANCH_NAME.yaml", "appengine/datastore-backup/app.yaml"]
- name: 'gcr.io/cloud-builders/gsutil'
  args: ["cp", "appengine/email-data/app.$BRANCH_NAME.yaml", "appengine/email-data/app.yaml"]
# deploy the app engine instances
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'appengine/form_data', 'appengine/form_data_paperform', 'appengine/email-data', 'appengine/cron.yaml']
  timeout: '600s'
