version: "3"

services:
  flatten-script:
    container_name: flatten-script
    restart: always
    build:
        context: .
        dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - "./src:/src"
