project_id_master: flatten-271620
project_id_staging: flatten-staging-271921
somalia:
  upload_file: somalia_data.json
  ds_kind: PaperformSubmission-so
  master:
    bucket: flatten-dataset
    ds_namespace: flatten_production
  staging:
    bucket: flatten-staging-dataset
    ds_namespace: flatten_staging
form_data:
  master:
    GCS_BUCKETS: flatten-271620.appspot.com,montreal-data,flatten-dataset"
    GCS_PATHS: ",form-data,form-data"
    CSV_BUCKET: flatten-dataset
    PREFIX: flatten-form-data-v1
  staging:
    GCS_BUCKETS: flatten-staging-271921.appspot.com,montreal-data-staging,flatten-staging-dataset
    GCS_PATHS: ",form-data,form-data"
    CSV_BUCKET: flatten-staging-dataset
    PREFIX: flatten-form-data-v1
insights_card:
  upload_file_ext: .svg
  upload_path: svg/
  download_file: fsa_img.json
  # same as in the node code for the backend - see src/utils/hash.js on that side
  image_hash_iterations: 100000
  image_hash_algorithm: sha512
  image_hash_digest: 64
  master:
    image_hash_secret: projects/81735388662/secrets/image-secret/versions/latest
    image_bucket: flatten-img-staging
  staging:
    image_hash_secret: projects/233853318753/secrets/image-secret/versions/latest
    image_bucket: flatten-img-staging
  master:
insights_data:
  UPLOAD_FILE: insights_data.json
  master:
    CSV_BUCKET: flatten-dataset
    PREFIX: flatten-form-data-v1
    UPLOAD_BUCKET: flatten-271620.appspot.com
  staging:
    CSV_BUCKET: flatten-staging-dataset
    PREFIX: flatten-form-data-v1
    UPLOAD_BUCKET: flatten-staging-271921.appspot.com
somalia_sheet:
  master:
    sheet_id: 1ZFoOztdR9Mt7Jb8dPSxAI05vW4VWAyENU3CrDc2PjlE
    bucket: flatten-dataset
  staging:
    sheet_id: 16cVSGjBRQns1eOrrVmZ-DDRR3LEYGQn-B2J8PXXlBJw
    bucket: flatten-staging-dataset
